name: Build Plugins

on:
  push:
    branches:
      - master   # changed from main to master
  pull_request:
    branches:
      - master   # changed from main to master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master   # explicitly checkout master branch
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload plugin
        run: |
          mkdir -p builds
          cp app/build/outputs/apk/release/app-release.apk builds/plugin.apk
          echo '[{"name":"YouTube Piped","description":"Unofficial YouTube provider using Piped API","version":1,"url":"https://raw.githubusercontent.com/looknorook/YUCHOB/builds/plugin.apk","author":"John"}]' > builds/plugins.json
      - name: Push builds branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin
          git checkout -B builds
          git add builds/*
          git commit -m "Update builds"
          git push origin builds --force
